---
- name: 解压 node.js 
  unarchive: 
    src: node-v12.13.1-linux-x64.tar.xz
    dest: /usr/local/

- name: 配置环境变量
  lineinfile:
    path: /etc/profile
    line: 'export NODE_HOME=/usr/local/node-v12.13.1-linux-x64'
    create: yes

- name: 配置环境变量
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:$NODE_HOME/bin'
    create: yes

- name: 配置环境变量
  lineinfile:
    path: /etc/profile
    line: 'export NODE_PATH=$NODE_HOME/lib/node_modules'
    create: yes

- name: 立即生效
  shell: source /etc/profile

- name: 配置环境变量
  lineinfile:
    path: ~/.bashrc
    line: 'export NODE_HOME=/usr/local/node-v12.13.1-linux-x64'
    create: yes

- name: 配置环境变量
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:$NODE_HOME/bin'
    create: yes

- name: 配置环境变量
  lineinfile:
    path: ~/.bashrc
    line: 'export NODE_PATH=$NODE_HOME/lib/node_modules'
    create: yes

- name: 立即生效
  shell: source ~/.bashrc

- name: 验证安装
  shell: node -v
  register: nodeVersion
  
- name: 输出 node.js 版本
  debug: 
    var: nodeVersion.stdout

# 更换 npm 源为阿里源
- name: 更换 npm 源为阿里源
  shell: npm config set registry https://registry.npm.taobao.org