---
# 安装 elasticsearch 

- name: 创建 elasticsearch 数据目录
  file: 
    path: '{{ path_data }}'
    state: directory
    mode: '0755'

- name: 创建 elasticsearch 日志目录
  file: 
    path: '{{ path_logs }}'
    state: directory
    mode: '0755'    

- name: 复制 elasticsearch-6.8.5.rpm 到 /usr/local/
  copy: 
    src: elasticsearch-6.8.5.rpm
    dest: /usr/local/elasticsearch-6.8.5.rpm
    
- name: 安装 elasticsearch
  yum: 
    name: /usr/local/elasticsearch-6.8.5.rpm
    state: present

- name: 设置 elasticsearch 主目录权限
  file:
    dest: '{{ elasticsearch_homepath }}'
    owner: elasticsearch
    group: elasticsearch
    recurse: yes

- name: 配置 elasticsearch 
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: 服务重载
  systemd: 
    daemon-reload: yes

- name: 启动 && 开机启动 elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: 等待 elasticsearch 启动
  wait_for:
    # host: 0.0.0.0
    port: 9200
    delay: 10
    # state: drained

# - name: 休眠 10 秒
#   wait_for:
#     timeout: 10
#   delegate_to: localhost

- name: 检查 elasticsarch 
  uri: 
    url: "http://127.0.0.1:{{ http_port }}"
    # url: "http://{{ ansible_default_ipv4.address }}:{{ http_port }}"
  register: curlOutput
  
- name: 输出检查结果
  debug: 
    var: curlOutput